# Generated by Django 4.2.2 on 2023-07-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motivacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poemo",
            name="img",
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name="poemo",
            name="poema_text",
            field=models.TextField(max_length=5000),
        ),
    ]
