# Generated by Django 4.2.2 on 2023-06-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("letra", models.CharField(max_length=500)),
                ("img", models.CharField(max_length=1000000000000)),
                ("url", models.URLField(blank=True)),
                ("fecha", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
