# Generated by Django 4.2.2 on 2023-06-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("escritor", models.CharField(max_length=50)),
                ("titulo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("poema_text", models.CharField(max_length=500)),
                ("img", models.CharField(max_length=100000)),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
